### ISSUE TITLE
PointCloud has NaN values but is_dense is true

### ISSUE THREAD

**Issue by kedingp** [nerian-vision/nerian_stereo#11]
is_dense should be false if PointCloud has Nan values:
http://pointclouds.org/documentation/tutorials/basic_structures.php#id9

This leads to problems if you subsequently process the point cloud. Could be solved by setting is_dense to false in line 393 of nerian_stereo_node.cpp.

**Comment by nerian-vision** [comment]
You are right. We've fixed it in the repository. It will be part of the next release.
