### ISSUE TITLE
Driver is not very out-of-the-box friendly

### ISSUE THREAD

**Issue by GrantDare** [nerian-vision/nerian_stereo#14]
Hi Team,

I am using your driver with a nerian sp1 and thus I am using v2.2.0 as per your recommendation to use a version prior to v3. I am trying to integrate this tech with RTABMap of which for stereo implementation requires a source of sensor_msgs::CameraInfo for each camera. This is provided inside a custom message of your package, nerian_stereo::StereoCameraInfo. I would like to recommend to make it more user friendly, extract this information and publish it in more usable formats. I don't feel like I should have to write my own node to convert the driver information into something usable.

Thanks.

**Comment by nerian-vision** [comment]
Dear GrantDare,

I am sorry that you are having difficulties using the camera info. The problem is that sensor_msgs::CameraInfo is only for a monocular camera and we are using a stereo camera. There is no existing message declaration in ROS for stereo cameras, which is why we had to create our own. The nerian_stereo::StereoCameraInfo node also contains information about the relative camera alignment, which is incredibly important for stereo vision. So just publishing two sensor_msgs::CameraInfo  messages will not be enough. Also, if we split the camera information up into at least 3 messages, then this brings along the problem of synchronization.

In your case I would recommend to write a simple python script that receives the nerian_stereo::StereoCameraInfo message and sens out one or two sensor_msgs::CameraInfo

**Comment by GrantDare** [comment]
Hi, Thank you for your feedback.

I would disagree that there is no camera info support for stereo cameras. Directly from the [sensor_msgs/CameraInfo documentation](http://docs.ros.org/kinetic/api/sensor_msgs/html/msg/CameraInfo.html) page,

```
# Rectification matrix (stereo cameras only)
# A rotation matrix aligning the camera coordinate system to the ideal
# stereo image plane so that epipolar lines in both stereo images are
# parallel.
float64[9]  R # 3x3 row-major matrix
```

There is a field to the message that is of specific importance to the operation of stereo cameras. Furthermore, so that I can use this package and hardware with the [RTABMap](http://wiki.ros.org/rtabmap_ros) algorithm of which directly supports stereo sources, I have had to include Tx and Ty in the field `float64[12] P` of which is pertinent to the positioning of stereo cameras.

```
# Projection/camera matrix
#     [fx'  0  cx' Tx]
# P = [ 0  fy' cy' Ty]
#     [ 0   0   1   0]
```

As you have stated, the message supports monocular cameras of which the documentation specifies:

```
# For monocular cameras, Tx = Ty = 0. Normally, monocular cameras will
#  also have R = the identity and P[1:3,1:3] = K.
```

However, also specifies support for stereo pairs:
```
# For a stereo pair, the fourth column [Tx Ty 0]' is related to the
#  position of the optical center of the second camera in the first
#  camera's frame. We assume Tz = 0 so both cameras are in the same
#  stereo image plane. The first camera always has Tx = Ty = 0. For
#  the right (second) camera of a horizontal stereo pair, Ty = 0 and
#  Tx = -fx' * B, where B is the baseline between the cameras.
```

Each cameras' image should also be presented in their own frame_id as a child of the stereo pairs position. The mapping algorithm I am attempting to use does support the use of stereo cameras and thus requires the camera information of both the left and right camera. The algorithm defaults to looking for topics `stereo_namespace/left/camera_info` and `stereo_namespace/right/camera_info` suggesting. As I understand, your message `nerian_stereo/StereoCameraInfo` contains these translation fields and so it wouldn't be to great of a task to publish transforms for each frame of camera as well as publish the cameras information for direct integration into other packages that support stereo vision.

Thank you, Grant :)

**Comment by GrantDare** [comment]
To further add to the issues with this package, the disparity map is published as a [sensor_msgs::Image](http://docs.ros.org/api/sensor_msgs/html/msg/Image.html) whereas all interfacable packages require the message to be of type [stereo_msgs::DisparityImage](http://docs.ros.org/api/stereo_msgs/html/msg/DisparityImage.html).

**Comment by nerian-vision** [comment]
Well, the DisparityImage message is intended for floating point disparity maps, whereas we produce fixed point disparity maps. Se we cannot transition to this message type. Btw, the SP1 is actually end of life, so there won't be any updates on the ROS node for it.
