### ISSUE TITLE
Only a small part of the full image is zoomed and published as ROS topic

### ISSUE THREAD

**Issue by SubMishMar** [nerian-vision/nerian_stereo#15]
I do  not understand why the images obtained in the web interface and ros topics are different. The following screenshots show the difference.
![Screenshot from 2019-08-16 22-06-22](https://user-images.githubusercontent.com/28704031/63206038-3f764b80-c073-11e9-9152-4870ca615ee3.png)
![Screenshot from 2019-08-16 22-09-32](https://user-images.githubusercontent.com/28704031/63206039-42713c00-c073-11e9-9713-d0894bc9fb34.png)

As seen, the image displayed in rqt_image_view is super zoomed and shows only a small part of the entire image, which can be seen in the web interface. Please help me resolve this issue.

I am using a Karmin 2 stereo with 25 cm baseline with scenescan pro on my ubuntu 16.04 computer which runs ROS Kinetic.

P.S. The camera is upside down, so the image is rotated.

**Comment by nerian-vision** [comment]
Hi,

it looks like the RGB image is treated as greayscale. Hence the horizontal stretch. Can you please check which version of the ROS node you are using? RGB support is a feature that was not available in early versions of the ROS node and SceneScan firmware.

Can you also please check if the color is correctly represented in the pointclouds? You can visualize them with rviz.

**Comment by SubMishMar** [comment]
Hi, I think am using the version meant for ROS kinetic. I just cloned the source code available here: https://github.com/nerian-vision/nerian_stereo and used the master version. 

Yes, the pointcloud looks colored correctly but the images don't look as expected.

**Comment by nerian-vision** [comment]
We have tracked down the problem and it is fixed in the git repository. Please give it a try. We'll trigger a new release if ti works for you.

**Comment by SubMishMar** [comment]
Many thanks. It works :) :)
