### ISSUE TITLE
Difference in visualization in OpenCV( and rqt_image_view) and ROS RVIZ

### ISSUE THREAD

**Issue by SubMishMar** [nerian-vision/nerian_stereo#18]
The figure below shows the difference in visualization of the disparity map (rostopic: /nerian_stereo/disparity_map) in OpenCV(left) and ROS RVIZ(right). 
![Screenshot from 2019-08-28 04-10-11](https://user-images.githubusercontent.com/28704031/63842219-d384c480-c949-11e9-84e2-87bf83e8c6b8.png)

I do not understand why this is happening. I want the OpenCV visualization to be same as the ROS Visualization because the OpenCV version appears too dark. To Visualize in OpenCV I use the following lines of code. 
```
cv::Mat image_disp = cv_bridge::toCvShare(image_msg, image_msg->encoding)->image;
 cv::imshow("view", img_disp);
 cv::waitKey(1);
```
But the picture visible to be me on imshow()ing it same as the picture shown on the left half of the screenshot above. I will appreciate an explanation and a possible remedy.

**Comment by nerian-vision** [comment]
The problem is that our disparities are in unpacked 12-bit format (Mono12). For visualization it should be sufficient to scale the image by 16:

`cv::imshow("view", img_disp * 16);`

Btw, you can also enable color coding in the ROS node (parameter: color_code_disparity_map), which is great for visualization, but doesn't allow analysis of the map.

**Comment by SubMishMar** [comment]
@nerian-vision . Just want to double check with you. So the true disparity value is the value contained in image_disp before the multiplication of 16?

**Comment by nerian-vision** [comment]
Actually you need to **divide** the disparity map by 16 to get the true disparity. This is because the disparity map has a sub-pixel resolution of 1/16 pixel. This is also the reason why the disparity map requires 12 bits per pixel, for encoding disparities up to 255.

By multiplying the disparity map by 16, you bring the disparities into the value range of a 16-bit image. This is good for visualization, but if you want to do any analysis then you would need to divide by 16^2 = 256.

**Comment by SubMishMar** [comment]
So suppose the disparity map (the original one generated by scenepro, i.e. not multiplied by 16) shows that a particular pixel has value 3. So, its disparity value must be 3/16? And Since Depth = Bf/Disp. In this case Depth = 1.6124943463258518e+02*16/3 Which is approximately 860 units. I am wondering if I am correct or wrong while making this calculation and what could be the unit result deduced above.

**Comment by nerian-vision** [comment]
You should divide the disparity before the projection. If you want to do it afterwards, you need to multiply instead, as the disparity is in the denominator. If your baseline is measured in meters (which is the default for SceneScan), then your point is 2.5km away. This can be plausible as a disparity of 3/16 is very close to 0, and 0 is at infinity.

The projection math is actually described in the manual on pages 16 and 17:
https://nerian.com/support/documentation/downloads/scenescan_manual.pdf

**Comment by SubMishMar** [comment]
I think I understood what you are saying here. I just want to ask a few more questions because the disparity value I get doesn't correspond to the true depth I get from my LiDAR.

So, I listen to the topic `/nerian_stereo/disparity_map` in a ROS node written in CPP by using the following code snippet:

```
    void callback(const sensor_msgs::ImageConstPtr &image_msg) {
           image_in = cv_bridge::toCvShare(image_msg, image_msg->encoding)->image;
   }
```
I know that the point (450, 400) on the image belongs to an object (checkerboard here) which is about 3.5 meters away (as reported by lidar whose position wrt to the camera is calibrated). So, I add the following lines to my code snippet to access the disparity at the point mentioned above and converting it into depth by using the baseline value provided by the camera's webinterface.

```
    void callback(const sensor_msgs::ImageConstPtr &image_msg) {
           image_in = cv_bridge::toCvShare(image_msg, image_msg->encoding)->image;
           int disp_subpixels = (int)image_in.at<uchar>(450, 400); // this is 255
           double disp_pixels = (double)disp_subpixels/16;
           double depth = baseline/disp_pixels; // For the 25 cm karmin2 it is 1.6124943463258518e+02
   }
```
Doing this gives me a depth of 10.12 m, but actually the checkerboard is about 3.3-3.5 m away from my sensor.  What am I getting wrong here?

**Comment by SubMishMar** [comment]
Thanks for your inputs. I have one more question with reference to the depth error vs depth curve given here: https://nerian.com/support/resources/calculator/?true,10,false,6,2,1600,1200,true,1,true,800,592,true,6,2,false,65,0,false,1,0,5,0,200,false,false,0.5,0,true,25,1,true,false,256,0.25,256,4,5,0,1.5,#results

Please correct me if I am wrong, but I assume you are using the following formula here: 
errorZ = (errorDisp*Z^2)/(baseline*focal_length)

Please let me know if this is the correct formula for the graph given in the aforementioned link.

**Comment by nerian-vision** [comment]
Actually we project the disparity d and d + errorDisp. The depth error is then the difference between these two projected depths.

**Comment by SubMishMar** [comment]
Is errorDisp a constant(I believe it is)? If so, then what is the value?

**Comment by nerian-vision** [comment]
Yes this is a constant and it can be configured in the calculator (at the very bottom). By default we assume an error of 0.25 pixels.

**Comment by SubMishMar** [comment]
@nerian-vision thanks for answering these queries. Can you refer me to some articles where I can read a little bit in depth about stereo vision, disparity maps, etc? I know the basic but I do not quite understand yet how all the calculations were done in this page: https://nerian.com/support/resources/calculator/?true,10,false,6,2,1600,1200,true,1,true,800,592,true,6,2,false,65,0,false,1,0,5,0,200,false,false,0.5,0,true,25,1,true,false,256,0.25,256,4,5,0,1.5,#results

**Comment by nerian-vision** [comment]
I could recommend the book Multiple View Geometry:
https://www.amazon.com/Multiple-View-Geometry-Computer-Vision-ebook/dp/B00AKE1QK4
