### ISSUE TITLE
Reduced FPS

### ISSUE THREAD

**Issue by SubMishMar** [nerian-vision/nerian_stereo#19]
Hi,
For some reason unknown to me, the camera is dropping frames. Initially the fps was about 24-30 but now it has dropped to 9. Here is a screen shot from the log displayed on the web interface.[](url)
![Screenshot from 2019-11-07 21-09-11](https://user-images.githubusercontent.com/28704031/68446709-2927e980-01a3-11ea-9150-9911eafae671.png)
Can someone please help me to have the data streaming at its original promised fps?

P.S. The wire connections were re done to look for loose contacts, but the problem persists.

**Comment by nerian-vision** [comment]
There are a few possible causes for dropped frames:

1. The camera might be exposing for too long. If the exposure time is too long then the frame rate will reduce. If you are using the auto exposure then please try to set a maximum exposure time.

2. The trigger rate is too high for the configured resolution / disparity range. Please compare with the table on https://nerian.com/products/scenescan-stereo-vision/ and reduce the trigger rate if needed

3. The network might be too slow. Please use Jumbo Frames for high resolution  / high frame rate configurations.

**Comment by SubMishMar** [comment]
1. I tested with an increased exposure but it didn't help.
2. I don't actually find the table in the link you have mentioned above, please help me find it.
3. Actually we are using jumbo frames I believe, we are connecting to the Scene Scan Pro box directly via ethernet (no USB in bw).

Hoping for some quick help. We really want a higher FPS.

**Comment by nerian-vision** [comment]
You should reduce the exposure and not increase.

Please scroll down on the linked page to see the table. Here's the screenshot:

![Screenshot from 2020-02-04 17-40-44](https://user-images.githubusercontent.com/13942303/73765969-a0a2f000-4775-11ea-8177-c3a5a9675946.png)

What resolution have you configured?

**Comment by SubMishMar** [comment]
Currently I am using 800x592. I have done a factory reset and the exposure is at its factory set value. 

Yes, I have seen this table and I was expecting the fps to be 27 Hz, just as it was when we had bought the system but it has been working on 9-13 Hz over the past few months. We have done factory reset several times, checked for loose connections, used jumbo frames and yet the problem persists.

**Comment by nerian-vision** [comment]
Can you please download your device configuration (from the maintenance page) and attach it .

**Comment by SubMishMar** [comment]
Here it is.
[settings.zip](https://github.com/nerian-vision/nerian_stereo/files/4155068/settings.zip)

**Comment by nerian-vision** [comment]
There are some very odd settings configured. The right camera is at the default settings and the left camera has some deviating settings. I see that there is a throughput limit configured for the left left camera which can explain these problems. Please restore the camera default settings by pressing the "Apply" button in the camera selection.

**Comment by SubMishMar** [comment]
I pressed apply in the camera section but I do not see any change. Can you please check this setting file and let me know if any thing is off?

Thanks.

[settings.zip](https://github.com/nerian-vision/nerian_stereo/files/4163087/settings.zip)

**Comment by nerian-vision** [comment]
I only see 6 seconds of log data in that file. I would like to have a remote look at your system. Do you have TeamViewer? Please contact me directly at service@nerian.com

**Comment by SubMishMar** [comment]
I will set it up and let you know.
Thanks!
