### ISSUE TITLE
Question: stereo_msgs/DisparityImage message type

### ISSUE THREAD

**Issue by dejongyeong** [nerian-vision/nerian_stereo#23]
Hi, a few questions here that I would like to ask with regards to the published topics from the driver:

1. Would it be possible to extract and publish two separate camera info - left and right from /nerian_stereo/stereo_camera_info topic.

2. Would it be possible to subscribe to current topics and write some code in order to publish stereo_msgs/DisparityImage message type from the driver?

Thanks and looking forward to hear from the community.

**Comment by nerian-vision** [comment]
Hi!

you can use the following script to split the camera info into two separate topics:

```
#!/usr/bin/env python

# This script splits an incoming StereoCameraInfo message into two
# CameraInfo messages, making it easier to integrate the nerian_stereo
# node with existing nodes that process 2d camera data.

import rospy
from nerian_stereo.msg import StereoCameraInfo
from sensor_msgs.msg import CameraInfo

leftPub = 0
rightPub = 0

def callback(data):
    global leftPub;
    global rightPub;

    rospy.loginfo(rospy.get_caller_id() + ": Camera info received")
    leftPub.publish(data.left_info)
    rightPub.publish(data.right_info)

def listener():
    global leftPub;
    global rightPub;

    rospy.init_node('camera_info_splitter')
    rospy.Subscriber("/nerian_stereo/stereo_camera_info", StereoCameraInfo, callback)

    leftPub = rospy.Publisher('/nerian_stereo/left_camera_info', CameraInfo, queue_size=10)
    rightPub = rospy.Publisher('/nerian_stereo/right_camera_info', CameraInfo, queue_size=10)

    rospy.spin()

if __name__ == '__main__':
    listener()
```

Regarding your second question:
The problem with the DisparityImage topic is that it expects a floating point image. For our disparity maps we use fixed-point representation, where the lowest 4 bits of a 16-bit value represent the fractional component. It is possible to convert from fixed point to floating point (just divide by 16.0) but it will require computation time and double the data size.

**Comment by dejongyeong** [comment]
Hi @nerian-vision. Thanks for the guideline. Much appreciated.
