### ISSUE TITLE
Stereo launch parameter ignored

### ISSUE THREAD

**Issue by emielke12** [nerian-vision/nerian_stereo#25]
Recently set up stereo cameras (nerian) with SceneScan Pro. I can access the image just fine on the network interface, however, when I try to launch the stereo node via `roslaunch nerian_stereo nerian_stereo.launch device_address:=192.168.10.10 node_name:=nerian_stereo_01` I receive the following, and am unable to acquire images via ROS:

```
process[master]: started with pid [18448]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c36e1250-4f7f-11eb-ac75-38dead941d03
process[rosout-1]: started with pid [18459]
started core service [/rosout]
process[download_calib-2]: started with pid [18466]
process[nerian_stereo_01-3]: started with pid [18468]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3173  100  3173    0     0  3098k      0 --:--:-- --:--:-- --:--:-- 3098k
[download_calib-2] process has finished cleanly
log file: /home/emielke/.ros/log/c36e1250-4f7f-11eb-ac75-38dead941d03/download_calib-2*.log
[ INFO] [1609869575.094111284]: Connecting to 192.168.10.10 for parameter service
Enumeration contained a ParameterID for which no name is known: 1047
Parameter ignored; please ensure your libvisiontransfer is up to date.
Enumeration contained a ParameterID for which no name is known: 1048
Parameter ignored; please ensure your libvisiontransfer is up to date.
Enumeration contained a ParameterID for which no name is known: 1049
Parameter ignored; please ensure your libvisiontransfer is up to date.
[ INFO] [1609869575.098223823]: Setting initial parameters in the parameter server
[ INFO] [1609869575.190847991]: Updating dynamic_reconfigure defaults and limits
[ INFO] [1609869575.210703804]: Connecting to 192.168.10.10:7681 for data transfer
DataBlockProtocol: Warning: forward-compatible mode; will attempt to process image stream with unknown extra flags. Consider upgrading the client software.
```

I have updated firmware on the cameras (7.1.2) and am using the latest libvisiontransfer (8.3.0)

Any suggestions?

**Comment by nerian-vision** [comment]
The ROS node has its own libvisiontransfer. Given your logs, I would guess that you are using an old version of the ROS node, and hence an old version of libvisiontransfer. The latest version is 3.8.1 from July 2020.

**Comment by emielke12** [comment]
I cloned the latest repo from source (instead of binaries from ROS) and am getting the same behavior. 

Note:

using Ubuntu 18.04.5 and ROS Melodic

**Comment by emielke12** [comment]
Additional attempts:

- running `nvcom` utility allows me to see camera
- unable to use package examples (python or c++, tried opencv_example for both) 
- - it appears it get stuck at line 45 `transfer.collect_received_image_set()`, with the indefinite timeout (for python)
- - gets stuck after `Receiving image set` in c++ (didn't look up line number, but seems to be same spot)
- - c++ implementation also gives error `DataBlockProtocol: Warning: forward-compatible mode; will attempt to process image stream with unknown extra flags. Consider upgrading the client software.`

I am using firmware v7.1.2 (2020-12-10). I'm wondering if this is the forward-compatible issue it's referring to? Should I downgrade the firmware to a previous version? It looks like this repo's last update was 2020-07-30. I will try that next and update with results.

**Comment by nerian-vision** [comment]
The ROS node should be compatible to the latest firmware. I'm surprised about the warning too. Could it be that you still have an old version of libvisiontransfer somewhere on your system (perhaps installed with the binary ROS package) and that your self-built node uses this version instead of the built one?

**Comment by emielke12** [comment]
> The ROS node should be compatible to the latest firmware. 

I tried reverting to firmware v6.1.0 (2020-07-29) and was able to run the ros node with no errors. However, it still does not send the data through the ROS node (`rostopic echo` shows no data on left, right, or disparity map images). Here is the output from the launch script: 

```process[master]: started with pid [8765]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 40a5b210-54f2-11eb-9640-38dead941d03
process[rosout-1]: started with pid [8776]
started core service [/rosout]
process[download_calib-2]: started with pid [8779]
process[nerian_stereo_01-3]: started with pid [8781]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3173  100  3173    0     0  3098k      0 --:--:-- --:--:-- --:--:-- 3098k
[download_calib-2] process has finished cleanly
log file: /home/emielke/.ros/log/40a5b210-54f2-11eb-9640-38dead941d03/download_calib-2*.log
[ INFO] [1610468503.890321062]: Connecting to 192.168.10.10 for parameter service
[ INFO] [1610468503.894530726]: Setting initial parameters in the parameter server
[ INFO] [1610468503.989121773]: Updating dynamic_reconfigure defaults and limits
[ INFO] [1610468504.011531668]: Connecting to 192.168.10.10:7681 for data transfer
```

> Could it be that you still have an old version of libvisiontransfer somewhere on your system (perhaps installed with the binary ROS package) and that your self-built node uses this version instead of the built one?

I double check to make sure I had removed the binaries, and rebuilt the package. I also had installed the nerian libraries from source, and removed those as well. This behavior continued even with those changes.

**Comment by nerian-vision** [comment]
I have checked the current binary version of the ROS node and yes it does produce the mentioned warning with the current firmware. However, that warning has no effect on the functionality and the node works well with the current firmware. To make the warning disappear you could replace the source code tar-archive in the 3rd-party folder with the current download from the nerian website, but this is not needed.

When you run nvcom, does it only detect the device or are you also able to stream image data? If NVCom does not receive image data either then the most likely cause is that your computer does not receive Jumbo frames (in that case check the network settings).

I could offer to have a remote look at the system to diagnose the problem. Do you have team viewer installed? Please contact me directly at konstantin.schauwecker@nerian.com

**Comment by emielke12** [comment]
>When you run nvcom, does it only detect the device or are you also able to stream image data? If NVCom does not receive image data either then the most likely cause is that your computer does not receive Jumbo frames (in that case check the network settings).

It was the jumbo frames. I was trying to use an ethernet to usb adapter, which wasn't actually changing to jumbo frames. Using the computer ethernet card allows the image to come through. Thanks for the help and walking through this with me!
