### ISSUE TITLE
Error using ROS2 Time as reference

### ISSUE THREAD

**Issue by montagne52** [nerian-vision/nerian_stereo#27]
With the ROS2 driver I am experiencing an issue where selecting the ROS2 time as source (parameter 'ros_timestamps': True) results in the following runtime error: 

`can't subtract times with different time sources [1 != 2]`

Everything works perfectly fine when selecting the PTP time as source, i.e. setting 'ros_timestamps': False in the launch file. 

Is anyone else experiencing this issue or knows how to solve it?

Many thanks and kind regards.

**Comment by nerian-vision** [comment]
I wasn't able to reproduce your problem with my ROS2 installation. Which ROS2 version are you using?
Nevertheless I think I found the cause for this error. The latest commit should hopefully fix this.

There will be a new release in the next few days anyway, which will also include this fix.
