### ISSUE TITLE
IMU data not published 

### ISSUE THREAD

**Issue by aatinubu** [nerian-vision/nerian_stereo#29]
I am working with the Ruby stereo camera, and I want to use the IMU data from the camera. Unfortunately, it is not published over a ros topic. How do I enable it, please?

**Comment by nerian-vision** [comment]
The orientation that is calculated by the IMU is published as a TF. By default the frame id is "nerian_stereo". Is that what you need or are you looking for raw accelerometer/gyroscope readings?

**Comment by aatinubu** [comment]
> The orientation that is calculated by the IMU is published as a TF. By default the frame id is "nerian_stereo". Is that what you need or are you looking for raw accelerometer/gyroscope readings?

Thank you for your reply. 
I need the raw accelerometer so I can calculate the linear acceleration. The goal is to estimate the distance traveled.

**Comment by nerian-vision** [comment]
Unfortunately the raw data is currently not published by the ROS node. This is on the todo list, I see if we can prioritize this feature. At the moment, the raw IMU readings are only available through the DataChannelService in the API.

**Comment by aatinubu** [comment]
Thank you. I found the code implementation in the imu_data_channel_example.cpp file. I can easily write my own ros publisher node with that.
