### ISSUE TITLE
help regarding scenescan pro

### ISSUE THREAD

**Issue by srinath2468** [nerian-vision/nerian_stereo#3]
I am running the image view node while connected to the scenescan pro. I am able to view the images when i type in the url but not through the ros node. I have installed the correct packages and nodes. When i try to visualize a disparity or any image, only a grey screen is displayed.

**Comment by nerian-vision** [comment]
Sorry for not having spotted your post. Your problem sounds like you are running either an old firmware and a new version of the ROS node, or the other way round. Please contact our support at service@nerian.com if the issue is still present.
