### ISSUE TITLE
SIGILL when using official ROS package

### ISSUE THREAD

**Issue by Daejiv** [nerian-vision/nerian_stereo#4]
# System Information
OS: Ubuntu Xenial 18.04
ROS: melodic

# Bug
I'm using the official `ros-melodic-nerian-stereo` package from the ROS package repositories. However the node (or any executable using `libvisiontransfer`) immediately crashed due to SIGILL. The illegal instruction belongs to the AVX512 instruction set, which is unsupported on my CPU.

This is caused by compiling `libvisiontransfer` with `-march=native`. The ROS build bot CPUs seem to support this instruction set.

# Proposed Fix
Remove the `-march=native` flag from the `libvisiontransfer` build instructions, since a lot of systems currently do not support AVX512.

It may be reasonable to require a lower vector instruction set, i guess SSE2 should be supported almost always, to profit from the performance gain.

**Comment by nerian-vision** [comment]
Has been fixed. With version 3.1 the default compilation flags will be set to SSE4.1, which is needed for pixel format conversion.
