### ISSUE TITLE
Missing `curl` dependencies in shell scripts

### ISSUE THREAD

**Issue by andersfischernielsen** [nerian-vision/nerian_stereo#5]
It seems that `curl` is missing as a dependency in `package.xml` for `nerian_stereo`. 
I get `command not found` errors in the following scripts: 

https://github.com/nerian-vision/nerian_stereo/blob/70b8b3bb1d81c6ed1b381702574f2569ab80bdc2/scripts/config_device_passthru.sh#L7

https://github.com/nerian-vision/nerian_stereo/blob/70b8b3bb1d81c6ed1b381702574f2569ab80bdc2/scripts/config_device_rectify.sh#L7

https://github.com/nerian-vision/nerian_stereo/blob/70b8b3bb1d81c6ed1b381702574f2569ab80bdc2/scripts/config_device_stereo.sh#L7

https://github.com/nerian-vision/nerian_stereo/blob/70b8b3bb1d81c6ed1b381702574f2569ab80bdc2/scripts/download_calibration.sh#L7

**Comment by nerian-vision** [comment]
The issue will be fixed in the next upcoming release (3.2.1)
