### ISSUE TITLE
NameError: global name 'StereoCameraInfo' is not defined

### ISSUE THREAD

**Issue by eyildiz-ugoe** [nerian-vision/nerian_stereo#9]
I can't get the camera info through a ROS node since the message seems to be not defined. Do we need to include `nerian_stereo` as a dependency into our ROS packages? If yes, does adding these lines  to any `package.xml` suffice? Or do we need to do  more?

```
<build_depend>nerian_stereo</build_depend>
<exec_depend>nerian_stereo</exec_depend>
<build_export_depend>nerian_stereo</build_export_depend>

```

Because right now, `from nerian_stereo import *` is not recognized, and hence `NameError: global name 'StereoCameraInfo' is not defined` is thrown.

**Comment by nerian-vision** [comment]
I guess for a python program you also need a run_depend as it's not being built.

**Comment by eyildiz-ugoe** [comment]
It's `exec_depend` actually. (http://docs.ros.org/api/catkin/html/howto/format2/python_module_dependencies.html), which I added as shown above. Do I need to do something more than this apart from `catkin_make`, so that the message is recognized?

**Comment by eyildiz-ugoe** [comment]
Okay, got it working.

One has to add: `from nerian_stereo.msg import StereoCameraInfo` to the top of Python file to import the required message.
